"""inquiry quotation vertical slice

Revision ID: 20260904_0005
Revises: 20260903_0004
Create Date: 2026-09-04 17:45:35.784968
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260904_0005"
down_revision: str | None = "20260903_0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("sku", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("standard_cost", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("cost_currency", sa.String(length=3), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "char_length(cost_currency) = 3", name=op.f("ck_products_cost_currency_iso_length")
        ),
        sa.CheckConstraint(
            "standard_cost >= 0", name=op.f("ck_products_standard_cost_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "created_by"],
            ["organization_memberships.organization_id", "organization_memberships.user_id"],
            name="fk_products_organization_id_created_by_membership",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "updated_by"],
            ["organization_memberships.organization_id", "organization_memberships.user_id"],
            name="fk_products_organization_id_updated_by_membership",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_products_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("organization_id", "id", name=op.f("uq_products_organization_id_id")),
    )
    op.create_index(
        "uq_products_organization_id_sku_active",
        "products",
        ["organization_id", "sku"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "inquiries",
        sa.Column("opportunity_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("customer_reference", sa.String(length=120), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="OPEN", nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "status IN ('OPEN', 'QUOTING', 'CLOSED')", name=op.f("ck_inquiries_inquiry_status")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "company_id"],
            ["companies.organization_id", "companies.id"],
            name="fk_inquiries_organization_id_company_id_companies",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "created_by"],
            ["organization_memberships.organization_id", "organization_memberships.user_id"],
            name="fk_inquiries_organization_id_created_by_membership",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "opportunity_id"],
            ["opportunities.organization_id", "opportunities.id"],
            name="fk_inquiries_organization_id_opportunity_id_opportunities",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "updated_by"],
            ["organization_memberships.organization_id", "organization_memberships.user_id"],
            name="fk_inquiries_organization_id_updated_by_membership",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_inquiries_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inquiries")),
        sa.UniqueConstraint("organization_id", "id", name=op.f("uq_inquiries_organization_id_id")),
    )
    op.create_index(
        "ix_inquiries_organization_id_status_created_at",
        "inquiries",
        ["organization_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "quotations",
        sa.Column("quotation_number", sa.String(length=40), nullable=False),
        sa.Column("inquiry_id", sa.Uuid(), nullable=False),
        sa.Column("opportunity_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("accepted_version_id", sa.Uuid(), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "company_id"],
            ["companies.organization_id", "companies.id"],
            name="fk_quotations_organization_id_company_id_companies",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "created_by"],
            ["organization_memberships.organization_id", "organization_memberships.user_id"],
            name="fk_quotations_organization_id_created_by_membership",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "inquiry_id"],
            ["inquiries.organization_id", "inquiries.id"],
            name="fk_quotations_organization_id_inquiry_id_inquiries",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "opportunity_id"],
            ["opportunities.organization_id", "opportunities.id"],
            name="fk_quotations_organization_id_opportunity_id_opportunities",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "updated_by"],
            ["organization_memberships.organization_id", "organization_memberships.user_id"],
            name="fk_quotations_organization_id_updated_by_membership",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_quotations_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quotations")),
        sa.UniqueConstraint("organization_id", "id", name=op.f("uq_quotations_organization_id_id")),
        sa.UniqueConstraint(
            "organization_id", "inquiry_id", name=op.f("uq_quotations_organization_id_inquiry_id")
        ),
        sa.UniqueConstraint(
            "organization_id",
            "quotation_number",
            name=op.f("uq_quotations_organization_id_quotation_number"),
        ),
    )
    op.create_index(
        "ix_quotations_organization_id_created_at",
        "quotations",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "quotation_versions",
        sa.Column("quotation_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="DRAFT", nullable=False),
        sa.Column("is_current", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("base_currency_code", sa.String(length=3), nullable=False),
        sa.Column("exchange_rate", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=False),
        sa.Column("payment_terms", sa.Text(), nullable=True),
        sa.Column("delivery_terms", sa.Text(), nullable=True),
        sa.Column("subtotal", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("freight_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("total_cost", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("gross_profit", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("gross_margin", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'INTERNAL_REVIEW', 'SENT', 'CUSTOMER_REVIEW', "
            "'ACCEPTED', 'REJECTED', 'EXPIRED', 'SUPERSEDED')",
            name=op.f("ck_quotation_versions_quotation_version_status"),
        ),
        sa.CheckConstraint(
            "char_length(base_currency_code) = 3",
            name=op.f("ck_quotation_versions_base_currency_code_iso_length"),
        ),
        sa.CheckConstraint(
            "char_length(currency_code) = 3",
            name=op.f("ck_quotation_versions_currency_code_iso_length"),
        ),
        sa.CheckConstraint(
            "exchange_rate > 0", name=op.f("ck_quotation_versions_exchange_rate_positive")
        ),
        sa.CheckConstraint(
            "subtotal >= 0 AND total >= 0 AND total_cost >= 0",
            name=op.f("ck_quotation_versions_totals_non_negative"),
        ),
        sa.CheckConstraint(
            "version_number > 0", name=op.f("ck_quotation_versions_version_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "approved_by"],
            ["organization_memberships.organization_id", "organization_memberships.user_id"],
            name="fk_quotation_versions_organization_id_approved_by_membership",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "created_by"],
            ["organization_memberships.organization_id", "organization_memberships.user_id"],
            name="fk_quotation_versions_organization_id_created_by_membership",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "quotation_id"],
            ["quotations.organization_id", "quotations.id"],
            name="fk_quotation_versions_organization_id_quotation_id_quotations",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "updated_by"],
            ["organization_memberships.organization_id", "organization_memberships.user_id"],
            name="fk_quotation_versions_organization_id_updated_by_membership",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_quotation_versions_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quotation_versions")),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_quotation_versions_organization_id_id")
        ),
        sa.UniqueConstraint(
            "organization_id",
            "quotation_id",
            "id",
            name=op.f("uq_quotation_versions_organization_id_quotation_id_id"),
        ),
        sa.UniqueConstraint(
            "organization_id",
            "quotation_id",
            "version_number",
            name=op.f("uq_quotation_versions_organization_id_quotation_id_version_number"),
        ),
    )
    op.create_index(
        "uq_quotation_versions_accepted",
        "quotation_versions",
        ["organization_id", "quotation_id"],
        unique=True,
        postgresql_where=sa.text("status = 'ACCEPTED'"),
    )
    op.create_index(
        "uq_quotation_versions_current",
        "quotation_versions",
        ["organization_id", "quotation_id"],
        unique=True,
        postgresql_where=sa.text("is_current"),
    )
    op.create_foreign_key(
        "fk_quotations_accepted_version_belongs_to_quotation",
        "quotations",
        "quotation_versions",
        ["organization_id", "id", "accepted_version_id"],
        ["organization_id", "quotation_id", "id"],
        ondelete="RESTRICT",
    )
    op.create_table(
        "quotation_items",
        sa.Column("quotation_version_id", sa.Uuid(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("sku_snapshot", sa.String(length=80), nullable=False),
        sa.Column("description_snapshot", sa.Text(), nullable=False),
        sa.Column("unit_snapshot", sa.String(length=32), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("cost_currency", sa.String(length=3), nullable=False),
        sa.Column("cost_exchange_rate", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("freight_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("allocated_cost", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("line_subtotal", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("line_cost", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("line_gross_profit", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "char_length(cost_currency) = 3",
            name=op.f("ck_quotation_items_cost_currency_iso_length"),
        ),
        sa.CheckConstraint(
            "cost_exchange_rate > 0", name=op.f("ck_quotation_items_cost_exchange_rate_positive")
        ),
        sa.CheckConstraint("line_number > 0", name=op.f("ck_quotation_items_line_number_positive")),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_quotation_items_quantity_positive")),
        sa.CheckConstraint(
            "tax_amount >= 0 AND freight_amount >= 0 AND allocated_cost >= 0",
            name=op.f("ck_quotation_items_item_charges_non_negative"),
        ),
        sa.CheckConstraint(
            "unit_price >= 0 AND unit_cost >= 0",
            name=op.f("ck_quotation_items_unit_amounts_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "created_by"],
            ["organization_memberships.organization_id", "organization_memberships.user_id"],
            name="fk_quotation_items_organization_id_created_by_membership",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "product_id"],
            ["products.organization_id", "products.id"],
            name="fk_quotation_items_org_product",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "quotation_version_id"],
            ["quotation_versions.organization_id", "quotation_versions.id"],
            name="fk_quotation_items_org_version",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "updated_by"],
            ["organization_memberships.organization_id", "organization_memberships.user_id"],
            name="fk_quotation_items_organization_id_updated_by_membership",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_quotation_items_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quotation_items")),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_quotation_items_organization_id_id")
        ),
        sa.UniqueConstraint(
            "organization_id",
            "quotation_version_id",
            "line_number",
            name=op.f("uq_quotation_items_organization_id_quotation_version_id_line_number"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("quotation_items")
    op.drop_constraint(
        "fk_quotations_accepted_version_belongs_to_quotation", "quotations", type_="foreignkey"
    )
    op.drop_index(
        "uq_quotation_versions_current",
        table_name="quotation_versions",
        postgresql_where=sa.text("is_current"),
    )
    op.drop_index(
        "uq_quotation_versions_accepted",
        table_name="quotation_versions",
        postgresql_where=sa.text("status = 'ACCEPTED'"),
    )
    op.drop_table("quotation_versions")
    op.drop_index("ix_quotations_organization_id_created_at", table_name="quotations")
    op.drop_table("quotations")
    op.drop_index("ix_inquiries_organization_id_status_created_at", table_name="inquiries")
    op.drop_table("inquiries")
    op.drop_index(
        "uq_products_organization_id_sku_active",
        table_name="products",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("products")
    # ### end Alembic commands ###
