from enum import StrEnum


class DocumentType(StrEnum):
    SALES_CONTRACT = "SALES_CONTRACT"
    COMMERCIAL_INVOICE = "COMMERCIAL_INVOICE"
    PACKING_LIST = "PACKING_LIST"
    BILL_OF_LADING = "BILL_OF_LADING"
    CERTIFICATE_OF_ORIGIN = "CERTIFICATE_OF_ORIGIN"
    BOOKING_CONFIRMATION = "BOOKING_CONFIRMATION"
    OTHER = "OTHER"


class DocumentVersionStatus(StrEnum):
    PENDING_UPLOAD = "PENDING_UPLOAD"
    UPLOADED = "UPLOADED"
    SCANNING = "SCANNING"
    AVAILABLE = "AVAILABLE"
    REJECTED = "REJECTED"


class DocumentLinkTargetType(StrEnum):
    SALES_ORDER = "SALES_ORDER"
    SHIPMENT = "SHIPMENT"
    CUSTOMS_DECLARATION = "CUSTOMS_DECLARATION"
    TAX_REFUND_CASE = "TAX_REFUND_CASE"


SHIPMENT_DEPARTURE_REQUIRED_DOCUMENTS = frozenset(
    {DocumentType.COMMERCIAL_INVOICE, DocumentType.PACKING_LIST}
)
